<?php

namespace Database\Seeders;

use App\Models\TopikQuestion;
use App\Models\TopikQuestionOption;
use Illuminate\Database\Seeder;

/**
 * TOPIK 問題の初期データを投入する。
 *
 * question_type = 'topic'  : 무엇에 대한 내용입니까？ (Q31〜33 形式)
 *   - question_text に本文の 1〜2 文を格納する。空欄マーカーは不要。
 *
 * question_type = 'grammar': 빈칸에 들어갈 알맞은 것을 고르십시오 (Q34〜39 形式)
 *   - question_text 内の「( )」が空欄を表す。
 */
class TopikQuestionBulkSeeder extends Seeder
{
    public function run(): void
    {
        $questions = $this->questions();

        foreach ($questions as $q) {
            /** @var TopikQuestion $question */
            $question = TopikQuestion::query()->updateOrCreate(
                [
                    'question_text' => $q['question_text'],
                    'question_type' => $q['question_type'],
                    'level' => $q['level'],
                ],
                [
                    'level' => $q['level'],
                    'question_type' => $q['question_type'],
                    'question_text' => $q['question_text'],
                    'question_text_ja' => $q['question_text_ja'] ?? null,
                    'question_text_ja_filled' => $q['question_text_ja_filled'] ?? null,
                    'explanation_ja' => $q['explanation_ja'] ?? null,
                    'status' => 'published',
                ],
            );

            foreach ($q['options'] as $optionData) {
                TopikQuestionOption::query()->updateOrCreate(
                    [
                        'question_id' => $question->id,
                        'option_number' => $optionData['option_number'],
                    ],
                    [
                        'question_id' => $question->id,
                        'option_number' => $optionData['option_number'],
                        'text' => $optionData['text'],
                        'text_ja' => $optionData['text_ja'] ?? null,
                        'is_correct' => $optionData['is_correct'],
                    ],
                );
            }
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function questions(): array
    {
        return [
            // ── TOPIK 1 主題問題 (Q31〜33 形式) ──────────────────────────────────
            // 무엇에 대한 내용입니까？ — 1〜2 文の内容が何について書かれているかを選ぶ
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 영국 사람입니다. 친구는 중국 사람입니다.',
                'question_text_ja' => '私はイギリス人です。友達は中国人です。',
                'explanation_ja' => '「영국 사람（イギリス人）」「중국 사람（中国人）」など国籍に関する内容なので、「나라（国）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '가족', 'text_ja' => '家族', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '날짜', 'text_ja' => '日付', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '나라', 'text_ja' => '国', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '학교', 'text_ja' => '学校', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '민수 씨는 의사입니다. 병원에서 일합니다.',
                'question_text_ja' => 'ミンスさんは医師です。病院で働きます。',
                'explanation_ja' => '「의사（医師）」「병원（病院）」など職業に関する内容なので、「직업（職業）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '요일', 'text_ja' => '曜日', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '직업', 'text_ja' => '職業', 'is_correct' => true],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '오늘은 비가 옵니다. 조금 춥습니다.',
                'question_text_ja' => '今日は雨が降ります。少し寒いです。',
                'explanation_ja' => '「비가 옵니다（雨が降ります）」「춥습니다（寒いです）」など天気に関する内容なので、「날씨（天気）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '운동', 'text_ja' => '運動', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '방학', 'text_ja' => '休暇', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '계획', 'text_ja' => '計画', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 불고기를 좋아합니다. 매일 먹습니다.',
                'question_text_ja' => '私はプルコギが好きです。毎日食べます。',
                'explanation_ja' => '「불고기（プルコギ）」「먹습니다（食べます）」など食べ物に関する内容なので、「음식（食べ物）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '운동', 'text_ja' => '運動', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 어제 백화점에 갔습니다. 옷을 샀습니다.',
                'question_text_ja' => '私は昨日デパートに行きました。服を買いました。',
                'explanation_ja' => '「백화점（デパート）」「옷을 샀습니다（服を買いました）」など買い物に関する内容なので、「쇼핑（ショッピング）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '학교', 'text_ja' => '学校', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '가족', 'text_ja' => '家族', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 축구를 합니다. 주말마다 친구들과 운동장에 갑니다.',
                'question_text_ja' => '私はサッカーをします。毎週末友達とグラウンドに行きます。',
                'explanation_ja' => '「축구（サッカー）」「운동장（グラウンド）」など運動・スポーツに関する内容なので、「운동（運動）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '운동', 'text_ja' => '運動', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 형과 누나가 있습니다. 우리는 같이 삽니다.',
                'question_text_ja' => '私にはお兄さんとお姉さんがいます。私たちは一緒に住んでいます。',
                'explanation_ja' => '「형（お兄さん）」「누나（お姉さん）」など家族に関する内容なので、「가족（家族）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '가족', 'text_ja' => '家族', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '날짜', 'text_ja' => '日付', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '요일', 'text_ja' => '曜日', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '직업', 'text_ja' => '職業', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 한국어를 배웁니다. 학교에서 공부합니다.',
                'question_text_ja' => '私は韓国語を学びます。学校で勉強します。',
                'explanation_ja' => '「한국어를 배웁니다（韓国語を学びます）」「학교에서 공부합니다（学校で勉強します）」など勉強に関する内容なので、「공부（勉強）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '공부', 'text_ja' => '勉強', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 1 文法問題（空欄補充）(Q34〜39 形式) ───────────────────────
            // ( ) に入る最も適切な語句を選ぶ
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '( )에 갑니다. 책을 삽니다.',
                'question_text_ja' => '（　）に行きます。本を買います。',
                'question_text_ja_filled' => '本屋に行きます。本を買います。',
                'explanation_ja' => '「책을 삽니다（本を買います）」から、本を売っている場所「서점（本屋）」が正解です。「은행（銀行）」「극장（劇場）」「식당（食堂）」は本を買う場所ではありません。',
                'options' => [
                    ['option_number' => 1, 'text' => '은행', 'text_ja' => '銀行', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '극장', 'text_ja' => '映画館', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '서점', 'text_ja' => '本屋', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '식당', 'text_ja' => '食堂', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '신발이 ( ). 발이 아픕니다.',
                'question_text_ja' => '靴が（　　）。足が痛いです。',
                'question_text_ja_filled' => '靴が小さいです。足が痛いです。',
                'explanation_ja' => '「발이 아픕니다（足が痛いです）」から、靴が「작습니다（小さいです）」ために足が痛いという文脈が自然です。',
                'options' => [
                    ['option_number' => 1, 'text' => '같습니다', 'text_ja' => '同じです', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '좋습니다', 'text_ja' => '良いです', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '작습니다', 'text_ja' => '小さいです', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '많습니다', 'text_ja' => '多いです', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '오후에 약속이 있습니다. 민수 씨를 ( ).',
                'question_text_ja' => '午後に約束があります。ミンスさんを（　　）。',
                'question_text_ja_filled' => '午後に約束があります。ミンスさんに会います。',
                'explanation_ja' => '「약속이 있습니다（約束があります）」から、민수 씨と「만납니다（会います）」が自然な流れです。',
                'options' => [
                    ['option_number' => 1, 'text' => '찍습니다', 'text_ja' => '撮ります', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '배웁니다', 'text_ja' => '学びます', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '모릅니다', 'text_ja' => '知りません', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '만납니다', 'text_ja' => '会います', 'is_correct' => true],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '이것은 제 가방이 아닙니다. 동생( ) 가방입니다.',
                'question_text_ja' => 'これは私のかばんではありません。弟・妹（　）かばんです。',
                'question_text_ja_filled' => 'これは私のかばんではありません。弟・妹のかばんです。',
                'explanation_ja' => '「동생（弟/妹）」に所有を表す助詞「의」がついて「동생의 가방（弟/妹のかばん）」となります。',
                'options' => [
                    ['option_number' => 1, 'text' => '도', 'text_ja' => 'も', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '만', 'text_ja' => 'だけ', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '의', 'text_ja' => 'の', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '을', 'text_ja' => 'を', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '회사에 일이 많습니다. ( ) 바쁩니다.',
                'question_text_ja' => '会社に仕事が多いです。（　　）忙しいです。',
                'question_text_ja_filled' => '会社に仕事が多いです。とても忙しいです。',
                'explanation_ja' => '「아주（とても）」は形容詞・副詞を修飾します。仕事がたくさんあるので「とても忙しい」という文脈が自然です。「빨리（早く）」「아까（さっき）」「먼저（先に）」は文意に合いません。',
                'options' => [
                    ['option_number' => 1, 'text' => '빨리', 'text_ja' => '早く', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '아까', 'text_ja' => 'さっき', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '먼저', 'text_ja' => '先に', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '아주', 'text_ja' => 'とても', 'is_correct' => true],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 학교( ) 가요.',
                'question_text_ja' => '私は学校（　）行きます。',
                'question_text_ja_filled' => '私は学校に行きます。',
                'explanation_ja' => '「에」は目的地・方向を表す助詞です。「에서」は行為が行われる場所、「에게」は人に対する助詞、「으로」は方向・手段を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '에', 'text_ja' => 'に', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '에서', 'text_ja' => 'で', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '에게', 'text_ja' => 'に（人）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '으로', 'text_ja' => 'へ・で', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 회사( ) 일해요.',
                'question_text_ja' => '私は会社（　）働きます。',
                'question_text_ja_filled' => '私は会社で働きます。',
                'explanation_ja' => '「에서」は行為が行われる場所を表す助詞です。「에」は目的地・時間・存在場所、「에게」は人への助詞、「이」は主語を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '에', 'text_ja' => 'に', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '에서', 'text_ja' => 'で', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '에게', 'text_ja' => 'に（人）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '이', 'text_ja' => 'が', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 지금 밥을 먹( ) 있어요.',
                'question_text_ja' => '私は今ご飯を食べ（　）います。',
                'question_text_ja_filled' => '私は今ご飯を食べています。',
                'explanation_ja' => '「고 있다」は進行形「〜している」を表す表現です。動詞の語幹に「고」をつけます。「아/어 있다」は状態の継続を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '아', 'text_ja' => 'て（아）', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '어', 'text_ja' => 'て（어）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '고', 'text_ja' => 'て（고）', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '서', 'text_ja' => 'て・から（서）', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '날씨가 더워( ) 에어컨을 켰어요.',
                'question_text_ja' => '天気が暑く（　）エアコンをつけました。',
                'question_text_ja_filled' => '天気が暑くてエアコンをつけました。',
                'explanation_ja' => '「서」は理由・原因を表す接続語尾です。「〜だから〜した」という意味になります。「지만」は逆接（〜だけど）、「면」は条件（〜なら）、「고」は並列（〜して）を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 밥을 먹( ) 싶어요.',
                'question_text_ja' => '私はご飯を食べ（　）です。',
                'question_text_ja_filled' => '私はご飯を食べたいです。',
                'explanation_ja' => '「고 싶다」は「〜したい」という願望を表す表現です。動詞の語幹に「고」をつけます。「서」は理由・継続、「지만」は逆接、「면」は条件を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 1 主題問題 追加分 ──────────────────────────────────────────
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 노래를 좋아합니다. 매일 음악을 듣습니다.',
                'question_text_ja' => '私は歌が好きです。毎日音楽を聴きます。',
                'explanation_ja' => '「노래（歌）」「음악（音楽）」など音楽に関する内容なので、「취미（趣味）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '공부', 'text_ja' => '勉強', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 오늘 병원에 갔습니다. 몸이 좋지 않았습니다.',
                'question_text_ja' => '私は今日病院に行きました。体の具合がよくありませんでした。',
                'explanation_ja' => '「병원（病院）」「몸이 좋지 않았습니다（体の具合がよくありませんでした）」など健康に関する内容なので、「건강（健康）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 버스를 탑니다. 지하철도 자주 이용합니다.',
                'question_text_ja' => '私はバスに乗ります。地下鉄もよく利用します。',
                'explanation_ja' => '「버스（バス）」「지하철（地下鉄）」など乗り物・交通に関する内容なので、「교통（交通）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '교통', 'text_ja' => '交通', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '직업', 'text_ja' => '職業', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '가족', 'text_ja' => '家族', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '오늘은 제 생일입니다. 친구들이 케이크를 사 줬습니다.',
                'question_text_ja' => '今日は私の誕生日です。友達がケーキを買ってくれました。',
                'explanation_ja' => '「생일（誕生日）」「케이크（ケーキ）」など誕生日に関する内容なので、「생일（誕生日）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '공부', 'text_ja' => '勉強', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '생일', 'text_ja' => '誕生日', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '운동', 'text_ja' => '運動', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 아파트에 삽니다. 방이 세 개 있습니다.',
                'question_text_ja' => '私はアパートに住んでいます。部屋が3つあります。',
                'explanation_ja' => '「아파트（アパート）」「방（部屋）」など住まいに関する内容なので、「집（家）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '집', 'text_ja' => '家', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'topic',
                'question_text' => '저는 주말에 영화를 봤습니다. 정말 재미있었습니다.',
                'question_text_ja' => '私は週末に映画を見ました。とても面白かったです。',
                'explanation_ja' => '「영화（映画）」「재미있었습니다（面白かったです）」などエンタメに関する内容なので、「영화（映画）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '공부', 'text_ja' => '勉強', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '영화', 'text_ja' => '映画', 'is_correct' => true],
                ],
            ],
            // ── TOPIK 1 文法問題（空欄補充）追加分 ──────────────────────────────
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 음악( ) 좋아해요.',
                'question_text_ja' => '私は音楽（　）好きです。',
                'question_text_ja_filled' => '私は音楽が好きです。',
                'explanation_ja' => '「을/를」は目的格助詞です。음악(音楽)は받침（パッチム）があるので「을」を使います。',
                'options' => [
                    ['option_number' => 1, 'text' => '이', 'text_ja' => 'が', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '가', 'text_ja' => 'が', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '을', 'text_ja' => 'を', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '에', 'text_ja' => 'に', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저기 고양이( ) 있어요.',
                'question_text_ja' => 'あそこに猫（　）います。',
                'question_text_ja_filled' => 'あそこに猫がいます。',
                'explanation_ja' => '「이/가」は主格助詞です。고양이(猫)は받침がないので「가」を使います。',
                'options' => [
                    ['option_number' => 1, 'text' => '가', 'text_ja' => 'が', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '이', 'text_ja' => 'が', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '을', 'text_ja' => 'を', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '는', 'text_ja' => 'は', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 한국어를 배워요. 중국어( ) 배워요.',
                'question_text_ja' => '私は韓国語を学びます。中国語（　）学びます。',
                'question_text_ja_filled' => '私は韓国語を学びます。中国語も学びます。',
                'explanation_ja' => '「도」は「も」を表す助詞です。前の文に続いて「中国語も学ぶ」という意味になります。',
                'options' => [
                    ['option_number' => 1, 'text' => '만', 'text_ja' => 'だけ', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '도', 'text_ja' => 'も', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '이', 'text_ja' => 'が', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '가', 'text_ja' => 'が', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '여기에 앉( )세요. 잠깐 기다려 주세요.',
                'question_text_ja' => 'ここにお座り（　）ください。少々お待ちください。',
                'question_text_ja_filled' => 'ここにお座りください。少々お待ちください。',
                'explanation_ja' => '「앉다」の語幹「앉」は받침があるので、「-(으)세요」は「으세요」になります。「앉으세요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '아', 'text_ja' => 'あ（語尾）', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '어', 'text_ja' => 'え（語尾）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '으', 'text_ja' => '으（語尾）', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 피아노를 칠 ( ) 있어요.',
                'question_text_ja' => '私はピアノを弾く（　）できます。',
                'question_text_ja_filled' => '私はピアノを弾くことができます。',
                'explanation_ja' => '「-(으)ㄹ 수 있다」は「〜することができる」を表す表現です。「수」が空欄に入ります。',
                'options' => [
                    ['option_number' => 1, 'text' => '수', 'text_ja' => 'こと（수）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '줄', 'text_ja' => 'こと（줄）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '것', 'text_ja' => 'こと（것）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '때', 'text_ja' => 'とき', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 고기를 먹( ) 않아요. 채소를 좋아해요.',
                'question_text_ja' => '私は肉を食べ（　）ません。野菜が好きです。',
                'question_text_ja_filled' => '私は肉を食べません。野菜が好きです。',
                'explanation_ja' => '「-지 않다」は「〜しない」を表す否定表現です。動詞の語幹に「지」をつけます。',
                'options' => [
                    ['option_number' => 1, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '지', 'text_ja' => 'ず・ない', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '저는 수영을 ( ) 해요. 배운 적이 없어요.',
                'question_text_ja' => '私は水泳が（　）できません。習ったことがありません。',
                'question_text_ja_filled' => '私は水泳ができません。習ったことがありません。',
                'explanation_ja' => '「못」は「〜できない」を表す副詞で、能力がないことを表します。「안」は意志的な否定です。',
                'options' => [
                    ['option_number' => 1, 'text' => '잘', 'text_ja' => 'うまく', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '못', 'text_ja' => '〜できない', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '안', 'text_ja' => '〜しない', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '더', 'text_ja' => 'もっと', 'is_correct' => false],
                ],
            ],
            [
                'level' => 1,
                'question_type' => 'grammar',
                'question_text' => '내일 꼭 전화할( )요.',
                'question_text_ja' => '明日必ず電話し（　）ます。',
                'question_text_ja_filled' => '明日必ず電話します。',
                'explanation_ja' => '「-(으)ㄹ게요」は「〜します（意志・約束）」を表す語尾です。「전화할게요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '거', 'text_ja' => 'こと・もの', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '게', 'text_ja' => 'ね（意志）', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '지', 'text_ja' => 'ず・ない', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 2（3〜4 級）主題問題 ───────────────────────────────────────
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 여름보다 겨울을 좋아합니다. 눈이 오는 날이 특히 좋습니다.',
                'question_text_ja' => '私は夏より冬が好きです。雪が降る日が特に好きです。',
                'explanation_ja' => '「여름（夏）」「겨울（冬）」「눈（雪）」など季節・天気に関する内容なので、「계절（季節）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '계절', 'text_ja' => '季節', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 2（3〜4 級）文法問題（空欄補充）───────────────────────────
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '회의가 끝나( ) 연락할게요.',
                'question_text_ja' => '会議が終わ（　）連絡します。',
                'question_text_ja_filled' => '会議が終わったら連絡します。',
                'explanation_ja' => '「(으)면」は条件「〜たら・〜なら」を表す接続語尾です。끝나다（終わる）の語幹「끝나」に「면」がつきます。「서」は理由・順序、「지만」は逆接、「고」は並列を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '시간이 없( ) 택시를 탔어요.',
                'question_text_ja' => '時間がな（　）タクシーに乗りました。',
                'question_text_ja_filled' => '時間がなくてタクシーに乗りました。',
                'explanation_ja' => '「아서/어서」は理由・原因を表す接続語尾です。없다（ない）は「없어서」になります。「지만」は逆接、「면」は条件、「고」は並列を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '어서', 'text_ja' => 'て・から', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '내일까지 제출해야 하( ) 지금 해야 해요.',
                'question_text_ja' => '明日までに提出しなければなら（　）今やらなければなりません。',
                'question_text_ja_filled' => '明日までに提出しなければならないので今やらなければなりません。',
                'explanation_ja' => '「(으)니까」は理由・根拠を表す接続語尾です。「〜だから〜しなければならない」という文脈に合います。「지만」は逆接、「면」は条件、「고」は並列を表します。',
                'options' => [
                    ['option_number' => 1, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '니까', 'text_ja' => 'だから', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 2（3〜4 級）主題問題 追加分 ──────────────────────────────
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 건강을 위해 매일 아침 운동합니다. 규칙적인 생활이 중요하다고 생각합니다.',
                'question_text_ja' => '私は健康のために毎朝運動します。規則正しい生活が大切だと思います。',
                'explanation_ja' => '「건강（健康）」「규칙적인 생활（規則正しい生活）」など健康に関する内容なので、「건강（健康）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '요즘 스마트폰 사용 시간이 늘고 있습니다. 특히 젊은 사람들 사이에서 많이 사용합니다.',
                'question_text_ja' => '最近スマートフォンの使用時間が増えています。特に若者の間でよく使われています。',
                'explanation_ja' => '「스마트폰（スマートフォン）」「사용 시간（使用時間）」など技術・スマートフォンに関する内容なので、「스마트폰（スマートフォン）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '스마트폰', 'text_ja' => 'スマートフォン', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 매주 도서관에서 책을 빌립니다. 다양한 장르의 책을 읽으려고 합니다.',
                'question_text_ja' => '私は毎週図書館で本を借ります。様々なジャンルの本を読もうとしています。',
                'explanation_ja' => '「도서관（図書館）」「책을 읽으려고（本を読もうと）」など読書に関する内容なので、「독서（読書）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '독서', 'text_ja' => '読書', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '한국 음식 중에서 김치가 세계적으로 유명합니다. 발효 식품으로 건강에도 좋습니다.',
                'question_text_ja' => '韓国料理の中でキムチが世界的に有名です。発酵食品として健康にも良いです。',
                'explanation_ja' => '「김치（キムチ）」「발효 식품（発酵食品）」など食べ物に関する内容なので、「음식（食べ物）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '문화', 'text_ja' => '文化', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 서울에서 부산으로 여행을 갔습니다. 기차로 2시간 반이 걸렸습니다.',
                'question_text_ja' => '私はソウルから釜山へ旅行に行きました。電車で2時間半かかりました。',
                'explanation_ja' => '「서울에서 부산으로（ソウルから釜山へ）」「기차（電車）」など旅行・移動に関する内容なので、「여행（旅行）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '교통', 'text_ja' => '交通', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '한국에서는 설날과 추석이 중요한 명절입니다. 가족이 모여서 음식을 만들고 이야기를 나눕니다.',
                'question_text_ja' => '韓国ではソルラル（旧正月）とチュソクが重要な祝日です。家族が集まって料理を作り話をします。',
                'explanation_ja' => '「설날（旧正月）」「추석（チュソク）」「명절（祝日）」など伝統行事に関する内容なので、「명절（祝日）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '명절', 'text_ja' => '祝日・行事', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 주말에 친구들과 영화를 봅니다. 특히 액션 영화를 좋아합니다.',
                'question_text_ja' => '私は週末に友達と映画を見ます。特にアクション映画が好きです。',
                'explanation_ja' => '「영화（映画）」「주말（週末）」など趣味・余暇活動に関する内容なので、「취미（趣味）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '쇼핑', 'text_ja' => 'ショッピング', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '교통', 'text_ja' => '交通', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '요즘 대학교 입학 경쟁이 심합니다. 많은 학생들이 공부를 열심히 합니다.',
                'question_text_ja' => '最近大学入学の競争が激しいです。多くの学生が一生懸命勉強しています。',
                'explanation_ja' => '「대학교 입학（大学入学）」「공부를 열심히（一生懸命勉強）」など教育に関する内容なので、「교육（教育）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '교육', 'text_ja' => '教育', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '한국에서는 지하철이 편리합니다. 시내 곳곳에 역이 있어서 어디든 갈 수 있습니다.',
                'question_text_ja' => '韓国では地下鉄が便利です。市内の至る所に駅があってどこでも行けます。',
                'explanation_ja' => '「지하철（地下鉄）」「역（駅）」など交通に関する内容なので、「교통（交通）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '교통', 'text_ja' => '交通', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '음식', 'text_ja' => '食べ物', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '여행', 'text_ja' => '旅行', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '날씨', 'text_ja' => '天気', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'topic',
                'question_text' => '저는 환경 문제에 관심이 많습니다. 쓰레기를 줄이기 위해 노력합니다.',
                'question_text_ja' => '私は環境問題に関心が高いです。ゴミを減らすために努力しています。',
                'explanation_ja' => '「환경 문제（環境問題）」「쓰레기를 줄이기（ゴミを減らす）」など環境に関する内容なので、「환경（環境）」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '취미', 'text_ja' => '趣味', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '환경', 'text_ja' => '環境', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '건강', 'text_ja' => '健康', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '교육', 'text_ja' => '教育', 'is_correct' => false],
                ],
            ],
            // ── TOPIK 2（3〜4 級）文法問題（空欄補充）追加分 ────────────────────
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '다음 달에 한국 여행을 가( ) 해요. 지금 계획을 세우고 있어요.',
                'question_text_ja' => '来月韓国旅行に行（　）います。今計画を立てています。',
                'question_text_ja_filled' => '来月韓国旅行に行こうとしています。今計画を立てています。',
                'explanation_ja' => '「-(으)려고 하다」は「〜しようとする・〜するつもりだ」という意図を表す表現です。「가려고 하다」になります。',
                'options' => [
                    ['option_number' => 1, 'text' => '려고', 'text_ja' => '〜しようと', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '는데', 'text_ja' => 'けど・が', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '면서', 'text_ja' => '〜しながら', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고서', 'text_ja' => '〜してから', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '저 사람은 학생인 ( ) 같아요. 가방을 들고 있어요.',
                'question_text_ja' => 'あの人は学生（　）ようです。カバンを持っています。',
                'question_text_ja_filled' => 'あの人は学生のようです。カバンを持っています。',
                'explanation_ja' => '「-(으)ㄴ/는 것 같다」は「〜のようだ」という推測を表す表現です。「것」が空欄に入ります。',
                'options' => [
                    ['option_number' => 1, 'text' => '것', 'text_ja' => 'こと・もの', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '수', 'text_ja' => 'こと（可能）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '만', 'text_ja' => 'だけ', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '때', 'text_ja' => 'とき', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '여기서 담배를 피우( ) 안 돼요.',
                'question_text_ja' => 'ここでタバコを吸っ（　）いけません。',
                'question_text_ja_filled' => 'ここでタバコを吸ってはいけません。',
                'explanation_ja' => '「-(으)면 안 되다」は「〜してはいけない」という禁止を表す表現です。「피우면 안 돼요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '어서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '면', 'text_ja' => 'たら・と', 'is_correct' => true],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '여기에 앉아( ) 돼요? 자리가 있어요?',
                'question_text_ja' => 'ここに座っ（　）いいですか？席はありますか？',
                'question_text_ja_filled' => 'ここに座ってもいいですか？席はありますか？',
                'explanation_ja' => '「-(아/어)도 되다」は「〜してもよい」という許可を表す表現です。「앉아도 돼요?」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '도', 'text_ja' => 'ても', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '야', 'text_ja' => '〜しなければ', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '면', 'text_ja' => 'たら・なら', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '내일 시험이 있어서 공부해( ) 해요.',
                'question_text_ja' => '明日試験があるので勉強し（　）なりません。',
                'question_text_ja_filled' => '明日試験があるので勉強しなければなりません。',
                'explanation_ja' => '「-(아/어)야 하다」は「〜しなければならない」という義務を表す表現です。「공부해야 해요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 2, 'text' => '야', 'text_ja' => '〜しなければ', 'is_correct' => true],
                    ['option_number' => 3, 'text' => '도', 'text_ja' => 'ても', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '밥을 먹은 ( ) 커피를 마셔요.',
                'question_text_ja' => 'ご飯を食べた（　）コーヒーを飲みます。',
                'question_text_ja_filled' => 'ご飯を食べた後にコーヒーを飲みます。',
                'explanation_ja' => '「-(으)ㄴ 후에」は「〜した後に」を表す表現です。「먹은 후에」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '후에', 'text_ja' => '後に', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '전에', 'text_ja' => '前に', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '동안', 'text_ja' => '間・あいだ', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '부터', 'text_ja' => 'から（起点）', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '시간이 있을 ( ) 책을 읽어요.',
                'question_text_ja' => '時間があると（　）本を読みます。',
                'question_text_ja_filled' => '時間があるとき本を読みます。',
                'explanation_ja' => '「-(으)ㄹ 때」は「〜するとき」を表す表現です。「있을 때」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '때', 'text_ja' => 'とき', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '수', 'text_ja' => 'こと（可能）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '것', 'text_ja' => 'こと・もの', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '만', 'text_ja' => 'だけ', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '바쁘( ) 때문에 연락을 못 했어요.',
                'question_text_ja' => '忙し（　）ため連絡できませんでした。',
                'question_text_ja_filled' => '忙しいため連絡できませんでした。',
                'explanation_ja' => '「-기 때문에」は「〜だから・〜のために（理由）」を表す表現です。「바쁘기 때문에」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '기', 'text_ja' => 'こと（名詞形）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '어', 'text_ja' => 'て（語尾）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '밥을 먹( ) 텔레비전을 봐요.',
                'question_text_ja' => 'ご飯を食べ（　）テレビを見ます。',
                'question_text_ja_filled' => 'ご飯を食べながらテレビを見ます。',
                'explanation_ja' => '「-(으)면서」は「〜しながら」という同時進行を表す接続語尾です。「먹으면서」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '으면서', 'text_ja' => 'ながら', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '아서', 'text_ja' => 'て・から', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고서', 'text_ja' => 'してから', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '한국어를 배우다가 한국 문화에도 관심을 갖( ) 됐어요.',
                'question_text_ja' => '韓国語を学んでいるうちに、韓国文化にも関心を持つように（　）なりました。',
                'question_text_ja_filled' => '韓国語を学んでいるうちに、韓国文化にも関心を持つようになりました。',
                'explanation_ja' => '「-게 되다」は「〜するようになる」という変化を表す表現です。「갖게 됐어요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '게', 'text_ja' => '〜ように（変化）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '도', 'text_ja' => 'ても', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '어', 'text_ja' => 'て（語尾）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '지', 'text_ja' => 'ず・ない', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '방학 ( ) 한국 여행을 갔어요.',
                'question_text_ja' => '休暇（　）韓国旅行に行きました。',
                'question_text_ja_filled' => '休暇の間韓国旅行に行きました。',
                'explanation_ja' => '「-는 동안」は「〜している間」を表す表現です。「방학 동안」で「休暇の間」という意味になります。',
                'options' => [
                    ['option_number' => 1, 'text' => '동안', 'text_ja' => '間・あいだ', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '후에', 'text_ja' => '後に', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '전에', 'text_ja' => '前に', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '때문에', 'text_ja' => 'ために（理由）', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '오늘 같이 영화를 볼( )요?',
                'question_text_ja' => '今日一緒に映画を見ませ（　）か？',
                'question_text_ja_filled' => '今日一緒に映画を見ませんか？',
                'explanation_ja' => '「-(으)ㄹ까요?」は「〜しましょうか・〜しませんか」という提案や勧誘を表す表現です。「볼까요?」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '까', 'text_ja' => 'か（提案）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '게', 'text_ja' => 'ね（意志）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '거', 'text_ja' => 'こと・もの', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '지', 'text_ja' => 'ず・ない', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '저는 한국에서 살기( ) 했어요.',
                'question_text_ja' => '私は韓国に住む（　）決めました。',
                'question_text_ja_filled' => '私は韓国に住むことに決めました。',
                'explanation_ja' => '「-기로 하다」は「〜することにする・〜すると決める」という決定を表す表現です。「살기로 했어요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '로', 'text_ja' => '〜することに（決定）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '가', 'text_ja' => 'が（助詞）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '에', 'text_ja' => 'に（助詞）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '도', 'text_ja' => 'も（助詞）', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '열심히 연습한( ) 대회에서 1등을 했어요.',
                'question_text_ja' => '一生懸命練習した（　）大会で1位になりました。',
                'question_text_ja_filled' => '一生懸命練習したおかげで大会で1位になりました。',
                'explanation_ja' => '「-(으)ㄴ 덕분에」は「〜したおかげで」というポジティブな原因・理由を表す表現です。「연습한 덕분에」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '덕분에', 'text_ja' => 'おかげで', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '때문에', 'text_ja' => 'ために（理由）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '후에', 'text_ja' => '後に', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '동안', 'text_ja' => '間・あいだ', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '오늘은 날씨가 좋은( ) 같이 산책할까요?',
                'question_text_ja' => '今日は天気がいい（　）一緒に散歩しませんか？',
                'question_text_ja_filled' => '今日は天気がいいので一緒に散歩しませんか？',
                'explanation_ja' => '「-(으)ㄴ데/는데」は背景や状況を述べて提案・依頼につなげる接続語尾です。「좋은데」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '데', 'text_ja' => 'けど・が（背景）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '지만', 'text_ja' => 'が・けど', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '면서', 'text_ja' => 'ながら', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '고', 'text_ja' => 'て・して', 'is_correct' => false],
                ],
            ],
            [
                'level' => 2,
                'question_type' => 'grammar',
                'question_text' => '아이가 아이스크림을 먹( ) 싶어해요.',
                'question_text_ja' => '子供がアイスクリームを食べ（　）がっています。',
                'question_text_ja_filled' => '子供がアイスクリームを食べたがっています。',
                'explanation_ja' => '「-고 싶어하다」は第三者の願望「〜したがっている」を表す表現です。「먹고 싶어해요」が正解です。',
                'options' => [
                    ['option_number' => 1, 'text' => '고', 'text_ja' => 'て・して（連結）', 'is_correct' => true],
                    ['option_number' => 2, 'text' => '어', 'text_ja' => 'て（語尾）', 'is_correct' => false],
                    ['option_number' => 3, 'text' => '아', 'text_ja' => 'て（語尾）', 'is_correct' => false],
                    ['option_number' => 4, 'text' => '서', 'text_ja' => 'て・から', 'is_correct' => false],
                ],
            ],
        ];
    }
}
