<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class VocabularySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'term' => '먹다',
                'meaning_ja' => '食べる',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '저는 밥을 먹어요.',
                'example_translation_ja' => '私はご飯を食べます。',
                'status' => 'published',
            ],
            [
                'term' => '마시다',
                'meaning_ja' => '飲む',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '물을 마셔요.',
                'example_translation_ja' => '水を飲みます。',
                'status' => 'published',
            ],
            [
                'term' => '공부하다',
                'meaning_ja' => '勉強する',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '한국어를 공부해요.',
                'example_translation_ja' => '韓国語を勉強します。',
                'status' => 'published',
            ],
            [
                'term' => '가다',
                'meaning_ja' => '行く',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '학교에 가요.',
                'example_translation_ja' => '学校に行きます。',
                'status' => 'published',
            ],
            [
                'term' => '오다',
                'meaning_ja' => '来る',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '집에 와요.',
                'example_translation_ja' => '家に来ます。',
                'status' => 'published',
            ],
            [
                'term' => '보다',
                'meaning_ja' => '見る',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '영화를 봐요.',
                'example_translation_ja' => '映画を見ます。',
                'status' => 'published',
            ],
            [
                'term' => '좋다',
                'meaning_ja' => '良い',
                'pos' => 'adj',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '날씨가 좋아요.',
                'example_translation_ja' => '天気が良いです。',
                'status' => 'published',
            ],
            [
                'term' => '크다',
                'meaning_ja' => '大きい',
                'pos' => 'adj',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '방이 커요.',
                'example_translation_ja' => '部屋が大きいです。',
                'status' => 'published',
            ],
            [
                'term' => '작다',
                'meaning_ja' => '小さい',
                'pos' => 'adj',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '가방이 작아요.',
                'example_translation_ja' => 'かばんが小さいです。',
                'status' => 'published',
            ],
            [
                'term' => '빨리',
                'meaning_ja' => '早く',
                'pos' => 'adv',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '빨리 와요.',
                'example_translation_ja' => '早く来てください。',
                'status' => 'published',
            ],
            [
                'term' => '천천히',
                'meaning_ja' => 'ゆっくり',
                'pos' => 'adv',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '천천히 말해 주세요.',
                'example_translation_ja' => 'ゆっくり話してください。',
                'status' => 'published',
            ],
            [
                'term' => '그리고',
                'meaning_ja' => 'そして',
                'pos' => 'other',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '빵을 사고 그리고 우유도 샀어요.',
                'example_translation_ja' => 'パンを買って、そして牛乳も買いました。',
                'status' => 'published',
            ],
            [
                'term' => '하지만',
                'meaning_ja' => 'しかし',
                'pos' => 'other',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '가고 싶지만 시간이 없어요.',
                'example_translation_ja' => '行きたいですが時間がありません。',
                'status' => 'published',
            ],
            [
                'term' => '그래서',
                'meaning_ja' => 'それで',
                'pos' => 'other',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '비가 와요. 그래서 우산을 가져왔어요.',
                'example_translation_ja' => '雨が降っています。それで傘を持ってきました。',
                'status' => 'published',
            ],
            [
                'term' => '정말',
                'meaning_ja' => '本当に',
                'pos' => 'adv',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '정말 맛있어요.',
                'example_translation_ja' => '本当においしいです。',
                'status' => 'published',
            ],
            [
                'term' => '너무',
                'meaning_ja' => 'とても（過度に）',
                'pos' => 'adv',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '너무 피곤해요.',
                'example_translation_ja' => 'とても疲れています。',
                'status' => 'published',
            ],
            [
                'term' => '손을 씻다',
                'meaning_ja' => '手を洗う',
                'pos' => 'verb',
                'level' => 1,
                'entry_type' => 'phrase',
                'example_sentence' => '밥 먹기 전에 손을 씻어요.',
                'example_translation_ja' => 'ご飯を食べる前に手を洗います。',
                'status' => 'published',
            ],
            [
                'term' => '시간이 나다',
                'meaning_ja' => '時間ができる',
                'pos' => 'verb',
                'level' => 3,
                'entry_type' => 'phrase',
                'example_sentence' => '주말에 시간이 나면 같이 가요.',
                'example_translation_ja' => '週末に時間ができたら一緒に行きましょう。',
                'status' => 'published',
            ],
            [
                'term' => '마음에 들다',
                'meaning_ja' => '気に入る',
                'pos' => 'verb',
                'level' => 3,
                'entry_type' => 'phrase',
                'example_sentence' => '이 옷이 마음에 들어요.',
                'example_translation_ja' => 'この服が気に入りました。',
                'status' => 'published',
            ],
            [
                'term' => '눈이 높다',
                'meaning_ja' => '目が肥えている',
                'pos' => 'adj',
                'level' => 5,
                'entry_type' => 'idiom',
                'example_sentence' => '그 사람은 눈이 높아서 고르기 어려워요.',
                'example_translation_ja' => 'その人は目が肥えていて選ぶのが難しいです。',
                'status' => 'published',
            ],
            [
                'term' => '입이 무겁다',
                'meaning_ja' => '口が堅い',
                'pos' => 'adj',
                'level' => 5,
                'entry_type' => 'idiom',
                'example_sentence' => '그는 입이 무거워서 비밀을 잘 지켜요.',
                'example_translation_ja' => '彼は口が堅く、秘密をよく守ります。',
                'status' => 'published',
            ],
            [
                'term' => '발이 넓다',
                'meaning_ja' => '顔が広い',
                'pos' => 'adj',
                'level' => 6,
                'entry_type' => 'idiom',
                'example_sentence' => '선배는 발이 넓어서 아는 사람이 많아요.',
                'example_translation_ja' => '先輩は顔が広くて知り合いが多いです。',
                'status' => 'published',
            ],
            [
                'term' => '무엇',
                'meaning_ja' => '何',
                'pos' => 'pronoun',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '무엇을 해요?',
                'example_translation_ja' => '何をしますか？',
                'status' => 'published',
            ],
            [
                'term' => '이',
                'meaning_ja' => 'この',
                'pos' => 'determiner',
                'level' => 1,
                'entry_type' => 'word',
                'example_sentence' => '이 책은 재미있어요.',
                'example_translation_ja' => 'この本は面白いです。',
                'status' => 'published',
            ],
            [
                'term' => '의',
                'meaning_ja' => '〜の（所有・連体）',
                'pos' => 'particle',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '친구의 집에 갔어요.',
                'example_translation_ja' => '友達の家に行きました。',
                'status' => 'published',
            ],
            [
                'term' => '와/과',
                'meaning_ja' => '〜と（並列）',
                'pos' => 'particle',
                'level' => 2,
                'entry_type' => 'word',
                'example_sentence' => '친구와 영화관에 갔어요.',
                'example_translation_ja' => '友達と映画館に行きました。',
                'status' => 'published',
            ],
            [
                'term' => '아/어도 되다',
                'meaning_ja' => '〜してもよい',
                'pos' => 'other',
                'level' => 3,
                'entry_type' => 'phrase',
                'example_sentence' => '여기에 앉아도 돼요?',
                'example_translation_ja' => 'ここに座ってもいいですか？',
                'status' => 'published',
            ],
            [
                'term' => '아/어서',
                'meaning_ja' => '〜して（理由/順接）',
                'pos' => 'other',
                'level' => 3,
                'entry_type' => 'phrase',
                'example_sentence' => '늦어서 죄송합니다.',
                'example_translation_ja' => '遅れてすみません。',
                'status' => 'published',
            ],
            [
                'term' => '다행이다',
                'meaning_ja' => 'よかった（幸いだ）',
                'pos' => 'interjection',
                'level' => 4,
                'entry_type' => 'word',
                'example_sentence' => '비가 안 와서 다행이에요.',
                'example_translation_ja' => '雨が降らなくてよかったです。',
                'status' => 'published',
            ],
            [
                'term' => '계속',
                'meaning_ja' => 'ずっと（継続して）',
                'pos' => 'adv',
                'level' => 4,
                'entry_type' => 'word',
                'example_sentence' => '계속 공부하고 있어요.',
                'example_translation_ja' => 'ずっと勉強しています。',
                'status' => 'published',
            ],
            [
                'term' => '만약',
                'meaning_ja' => 'もし',
                'pos' => 'adv',
                'level' => 4,
                'entry_type' => 'word',
                'example_sentence' => '만약 시간이 있으면 연락해 주세요.',
                'example_translation_ja' => 'もし時間があれば連絡してください。',
                'status' => 'published',
            ],
            [
                'term' => '반드시',
                'meaning_ja' => '必ず',
                'pos' => 'adv',
                'level' => 5,
                'entry_type' => 'word',
                'example_sentence' => '약은 반드시 식후에 드세요.',
                'example_translation_ja' => '薬は必ず食後に飲んでください。',
                'status' => 'published',
            ],
            [
                'term' => '대체로',
                'meaning_ja' => '概して',
                'pos' => 'adv',
                'level' => 6,
                'entry_type' => 'word',
                'example_sentence' => '대체로 사람들은 친절해요.',
                'example_translation_ja' => '概して人々は親切です。',
                'status' => 'published',
            ],
        ];

        foreach ($items as $item) {
            Vocabulary::query()->firstOrCreate(
                [
                    'term' => $item['term'],
                    'pos' => $item['pos'],
                    'meaning_ja' => $item['meaning_ja'],
                ],
                $item,
            );
        }
    }
}
